### PR TITLE
Setup tests

### PR DESCRIPTION
**Pull request by filipemerker**
Hey, as I said in my issue, loved the repo and I hope to see it become the next thing.

Here I set up the testing environment (using testing-library, since the whole thing is inspired by KCD 😊) and write two integration tests for createStore.

I plan on doing more over time, but I wanted to validate the style and the approach with you first.

Hope it helps.

### CODE REVIEW

**Comment by Aslemammad** [comment]
I appreciate this, The project will improve with you. I have a request, Can you do the rest of the test for other functions too( like useContext, ...).

**Comment by Aslemammad** [comment]
Share the project with your friends too. I loved the Tests.

**Comment by filipemerker** [comment]
Sure, I'll do that this week. (:

**Comment by Aslemammad** [comment]
♥️

**Pull request merged**
